- name: ping the server
  hosts: frontend # which server you are connecting to
  # list of tasks/collections/modules
  tasks:
  - name: ping
    ansible.builtin.ping: 



#    - name: PLAY-01
 #     hosts: frontend
 #     tasks:
 #    - name: PLAY-01 and TASK-01
 #      ansible.builtin.debug:
 #      msg: "Hello from PLAY-01 and TASK-01"

- name: play-01
  hosts: frontend
  tasks:
  - name: play-01
    ansible.builtin.debug:



    - name: play level variables
  hosts: local
  connection: local # ansible is connecting to local host
  vars:
    COURSE: DEVOPS WITH AWS
    DURATION: 10HRS
    Trainer: Sivakumar
  tasks:
  - name: print the course info
    vars:
      COURSE: ansible
    ansible.builtin.debug:
      msg: "Course Name is: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ Trainer }}"