- name: ping the server
  hosts: frontend # which server you are connecting to
  # list of tasks/collections/modules
  tasks:
  - name: ping
    ansible.builtin.ping: 



#    - name: PLAY-01
 #     hosts: frontend
 #     tasks:
 #    - name: PLAY-01 and TASK-01
 #      ansible.builtin.debug:
 #      msg: "Hello from PLAY-01 and TASK-01"

- name: play-01
  hosts: frontend
  tasks:
  - name: play-01
    ansible.builtin.debug: