- name: play level variables
  hosts: local
  connection: local # ansible is connecting to local host
  vars:
    COURSE: ansible
    DURATION: 10HRS
    Trainer: Sivakumar
  tasks:
  - name: print the course info
    ansible.builtin.debug:
      msg: "Course Name is: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ Trainer }}" 


#- name: play-01
 # hosts: local
 # connection: local 
 # vars:
 #   COURSE: DEVOPS WITH AWS
 #   DURATION: 10HRS
 #   TRAINER: SIVA     
 # tasks:
 # - name: print the course info
 #   ansible.builtin.debug:
  #    msg: "Course Name is: {{ COURSE }}, duration is: {{ DURATION }}, trainer is: {{ TRAINER }}"