- name: variables from files
  hosts: local
  connection: local
  tasks: 
  - name: print course info
    ansible.builtin.debug:
      msg: "Course Name is: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ Trainer }}"



- name: variables from files
  hosts: local
  connection: local
  tasks: 
  - name: print course info
    ansible.builtin.debug:
      msg: "Course Name is: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ Trainer }}"


      # ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 -e "COURSE=AWS" -e "DURATION=80HRS" -e "TRAINER=SIVA"  08-vars-inventory.yaml

