- name: data types
  hosts: local 
  connection: local
  vars: 
    Course: "Devops with Aws"
    Duration: 120 # number
    is_live: true #boolean
    # list
    tools: #["linux", "shell", "ansible"]
    - "linux"
    - shell
    - ansible
    concepts: # dictonary or map
      cloud: aws
      cm: ansible
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "Course name: {{ Course }}, Duration: {{ Duration }}, is it live?: {{ is_live }}, tools are: {{ tools }} concepts are: {{ concepts }}"

#list: []
#map: {}

- name: data types
  hosts: local
  connection: local
  vars:
  Course: "AWS"
  Duration: 80
  is_live: true

  tools:
  - linux
  - shell
  - ansible

  concepts:
     cloud: aws
     cm: ansible
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "Course name: {{ Course }}, Duration is: {{ Duration }}, is it live? {{ is_live }}, tools are: {{ tools }}, concepts are: {{ concepts }}"   
